# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CeibaApp-IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CeibaApp-IOS
  pod 'Alamofire', '~> 5.2'
  target 'CeibaApp-IOSTests' do
    inherit! :search_paths
     
    # Pods for testing
  end

  target 'CeibaApp-IOSUITests' do
    # Pods for testing
  end

end
